<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNnukk1x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNnukk1x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNnukk1x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNnukk1x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNnukk1x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nnukk1x',
    'container.build_id' => 'c9181fd8',
    'container.build_time' => 1545712684,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNnukk1x');
