<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLgqvkgo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLgqvkgo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLgqvkgo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLgqvkgo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLgqvkgo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Lgqvkgo',
    'container.build_id' => '2f604e03',
    'container.build_time' => 1547931732,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLgqvkgo');
