<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKlopkme\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKlopkme/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKlopkme.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKlopkme\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKlopkme\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Klopkme',
    'container.build_id' => '27304aab',
    'container.build_time' => 1544537642,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKlopkme');
