<?php

namespace AppBundle\Repository;



use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findByLetters($string){
        return $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:Client c  
                WHERE c.name LIKE :string OR c.last_name LIKE :string')
            ->setParameter('string','%'.$string.'%')
            ->getResult();
    }
}
