<?php

namespace AppBundle\Repository;



use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{


public function getAvailableRooms($date_start,$date_final)

{




    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

    //$em = $qb->getEntityManager();


    $dql = $em->createQuery("SELECT IDENTITY (b.room) FROM AppBundle:Reservation b
          WHERE NOT (b.dateOut < '$date_start' OR b.dateIn > '$date_final')");




    $dql_query = $dql->getDQL();



    $qb->resetDQLParts();

    $query = $qb->select('r')
        ->from('AppBundle:Room', 'r')
        ->where($qb->expr()->notIn('r.id', $dql_query))
        //->set('dateIn', $date_start )
        //->set('dateOut', $date_final)
        ->getQuery();





    return $query;

}

}
