<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ZipCityStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ZipCityStateRepository extends EntityRepository
{

    public function getzipcitystate()
    {



        $qb = $this->createQueryBuilder('zip_city_state')
           // ->select('z')->from('AppBundle\Entity\ZipCityState','z')->distinct(true)
           // ->select('s')->from('AppBundle\Entity\ZipCityState','s')->distinct(true)
           ->select('s')->from('AppBundle\Entity\ZipCityState','s')
            ->addOrderBy('zip_city_state.zip', 'ASC')
            ->addOrderBy('zip_city_state.city', 'ASC')
            ->addOrderBy('zip_city_state.state', 'ASC')

            ->setMaxResults(3)

        ;
        $query = $qb->getQuery();

        return $query->execute();

    }


}
