<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ZipCityStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ZipCityStateRepository extends EntityRepository
{

    public function getzipcitystate()
    {



        $qb = $this->createQueryBuilder('zip_city_state')

           // ->select('z')->from('AppBundle\Entity\ZipCityState','z')->distinct(true) //not work
           // ->select('s')->from('AppBundle\Entity\ZipCityState','s')->distinct(true)  //not work

            ->addOrderBy('zip_city_state.zip', 'ASC')   //leave like option to customise
           // ->addOrderBy('zip_city_state.city', 'ASC')   //leave like option to customise
           //->addOrderBy('zip_city_state.state', 'ASC')   //leave like option to customise
           //->addOrderBy('zip_city_state.id', 'ASC')   //leave like option to customise
            ->setMaxResults(37080)

        ;
        $query = $qb->getQuery();

        return $query->execute();

    }


}
