<?php

namespace AppBundle\Repository;

/**
 * ZipCityStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCityStateRepository extends \Doctrine\ORM\EntityRepository
{
}
