AppBundle\Entity\Client:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '20'
            nullable: true
        name:
            type: string
            length: '100'
        last_name:
            type: string
            length: '100'
            column: last_name
        address:
            type: text
        zip_code:
            type: string
            length: '10'
            column: zip_code
        city:
            type: string
            length: '50'
        state:
            type: string
            length: '20'
        email:
            type: string
            length: '100'
            unique: true
        adult:
            type: integer
            length: '1'
            unique: true
        child:
            type: integer
            length: '1'
            unique: true
        baby:
            type: integer
            length: '1'
            unique: true
    lifecycleCallbacks: {  }
    oneToMany:
        reservations:
            targetEntity: Reservation
            cascade: [ remove ]
            mappedBy: client
