AppBundle\Entity\ZipCityState:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ZipCityStateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        zip:
            type: string
        city:
            type: string
            length: '255'
        state:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
