<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUnt61lh\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUnt61lh/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUnt61lh.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUnt61lh\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerUnt61lh\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Unt61lh',
    'container.build_id' => '5a838f52',
    'container.build_time' => 1544567743,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUnt61lh');
