<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOqv2e2m\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOqv2e2m/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOqv2e2m.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOqv2e2m\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerOqv2e2m\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Oqv2e2m',
    'container.build_id' => '03c84f7a',
    'container.build_time' => 1543698128,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOqv2e2m');
