<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKkkdwex\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKkkdwex/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKkkdwex.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKkkdwex\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKkkdwex\appProdProjectContainer(array(
    'container.build_hash' => 'Kkkdwex',
    'container.build_id' => '89f1fd04',
    'container.build_time' => 1545699058,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKkkdwex');
